export const mockGoods: Good[] = [
    {
        id: '1',
        name: 'Apple',
        note: 'Green',
        quantity: 5,
        unit: 'pcs',
        categories: ['Fruits'],
    },
    {
        id: '2',
        name: 'Orange',
        note: 'Sweet',
        quantity: 10,
        unit: 'pcs',
        categories: ['Fruits'],
    },
    {
        id: '3',
        name: 'Milk',
        note: '2.5%',
        quantity: 1,
        unit: 'l',
        categories: ['Dairy'],
    },
    {
        id: '4',
        name: 'Bread',
        note: 'Whole grain',
        quantity: 1,
        unit: 'pcs',
        categories: ['Bakery'],
    },
    {
        id: '5',
        name: 'Chicken',
        note: 'Breast',
        quantity: 2,
        unit: 'kg',
        categories: ['Meat'],
    },
    {
        id: '6',
        name: 'Tomato',
        note: 'Cherry',
        quantity: 250,
        unit: 'g',
        categories: ['Vegetables'],
    },
    {
        id: '7',
        name: 'Cucumber',
        note: 'Fresh',
        quantity: 1,
        unit: 'pcs',
        categories: ['Vegetables'],
    },
    {
        id: '8',
        name: 'Cheese',
        note: 'Cheddar',
        quantity: 200,
        unit: 'g',
        categories: ['Dairy'],
    },
    {
        id: '9',
        name: 'Eggs',
        note: 'Brown',
        quantity: 10,
        unit: 'pcs',
        categories: ['Dairy'],
    },
    {
        id: '10',
        name: 'Banana',
        note: 'Ripe',
        quantity: 1,
        unit: 'kg',
        categories: ['Fruits'],
    },
    {
        id: '11',
        name: 'Pasta',
        note: 'Spaghetti',
        quantity: 500,
        unit: 'g',
        categories: ['Pasta'],
    },
    {
        id: '12',
        name: 'Rice',
        note: 'Basmati',
        quantity: 1,
        unit: 'kg',
        categories: ['Grains'],
    },
    {
        id: '13',
        name: 'Potato',
        note: 'New',
        quantity: 2,
        unit: 'kg',
        categories: ['Vegetables'],
    },
    {
        id: '14',
        name: 'Onion',
        note: 'Yellow',
        quantity: 500,
        unit: 'g',
        categories: ['Vegetables'],
    },
    {
        id: '15',
        name: 'Carrot',
        note: 'Fresh',
        quantity: 500,
        unit: 'g',
        categories: ['Vegetables'],
    },
    {
        id: '16',
        name: 'Yogurt',
        note: 'Natural',
        quantity: 1,
        unit: 'kg',
        categories: ['Dairy'],
    },
    {
        id: '17',
        name: 'Salmon',
        note: 'Fresh',
        quantity: 1,
        unit: 'kg',
        categories: ['Fish'],
    },
    {
        id: '18',
        name: 'Butter',
        note: 'Unsalted',
        quantity: 200,
        unit: 'g',
        categories: ['Dairy'],
    },
    {
        id: '19',
        name: 'Beef',
        note: 'Sirloin',
        quantity: 1,
        unit: 'kg',
        categories: ['Meat'],
    },
    {
        id: '20',
        name: 'Lemon',
        note: 'Fresh',
        quantity: 5,
        unit: 'pcs',
        categories: ['Fruits'],
    },
    {
        id: '21',
        name: 'Pork',
        note: 'Loin',
        quantity: 1,
        unit: 'kg',
        categories: ['Meat'],
    },
    {
        id: '22',
        name: 'Lettuce',
        note: 'Iceberg',
        quantity: 1,
        unit: 'pcs',
        categories: ['Vegetables'],
    },
    {
        id: '23',
        name: 'Pepper',
        note: 'Bell',
        quantity: 500,
        unit: 'g',
        categories: ['Vegetables'],
    },
    {
        id: '24',
        name: 'Zucchini',
        note: 'Green',
        quantity: 1,
        unit: 'kg',
        categories: ['Vegetables'],
    },
    {
        id: '25',
        name: 'Cabbage',
        note: 'White',
        quantity: 1,
        unit: 'pcs',
        categories: ['Vegetables'],
    },
    {
        id: '26',
        name: 'Broccoli',
        note: 'Fresh',
        quantity: 500,
        unit: 'g',
        categories: ['Vegetables'],
    },
    {
        id: '27',
        name: 'Spinach',
        note: 'Baby',
        quantity: 200,
        unit: 'g',
        categories: ['Vegetables'],
    },
    {
        id: '28',
        name: 'Mushrooms',
        note: 'White',
        quantity: 250,
        unit: 'g',
        categories: ['Vegetables'],
    },
    {
        id: '29',
        name: 'Garlic',
        note: 'Fresh',
        quantity: 100,
        unit: 'g',
        categories: ['Vegetables'],
    },
    {
        id: '30',
        name: 'Honey',
        note: 'Acacia',
        quantity: 500,
        unit: 'g',
        categories: ['Sweets'],
    },
    {
        id: '31',
        name: 'Sugar',
        note: 'White',
        quantity: 1,
        unit: 'kg',
        categories: ['Sweets'],
    },
    {
        id: '32',
        name: 'Salt',
        note: 'Sea',
        quantity: 500,
        unit: 'g',
        categories: ['Spices'],
    },
    {
        id: '33',
        name: 'Pepper',
        note: 'Black',
        quantity: 100,
        unit: 'g',
        categories: ['Spices'],
    },
    {
        id: '34',
        name: 'Cinnamon',
        note: 'Ground',
        quantity: 50,
        unit: 'g',
        categories: ['Spices'],
    },
];
